import { KeyConfig } from './types';

// Simplified keyboard layout for visual reference
export const KEYBOARD_LAYOUT: KeyConfig[][] = [
  [
    { key: '1', finger: 'L-Pinky', row: 0, hand: 'left' },
    { key: '2', finger: 'L-Ring', row: 0, hand: 'left' },
    { key: '3', finger: 'L-Middle', row: 0, hand: 'left' },
    { key: '4', finger: 'L-Index', row: 0, hand: 'left' },
    { key: '5', finger: 'L-Index', row: 0, hand: 'left' },
    { key: '6', finger: 'R-Index', row: 0, hand: 'right' },
    { key: '7', finger: 'R-Index', row: 0, hand: 'right' },
    { key: '8', finger: 'R-Middle', row: 0, hand: 'right' },
    { key: '9', finger: 'R-Ring', row: 0, hand: 'right' },
    { key: '0', finger: 'R-Pinky', row: 0, hand: 'right' },
  ],
  [
    { key: 'q', finger: 'L-Pinky', row: 1, hand: 'left' },
    { key: 'w', finger: 'L-Ring', row: 1, hand: 'left' },
    { key: 'e', finger: 'L-Middle', row: 1, hand: 'left' },
    { key: 'r', finger: 'L-Index', row: 1, hand: 'left' },
    { key: 't', finger: 'L-Index', row: 1, hand: 'left' },
    { key: 'y', finger: 'R-Index', row: 1, hand: 'right' },
    { key: 'u', finger: 'R-Index', row: 1, hand: 'right' },
    { key: 'i', finger: 'R-Middle', row: 1, hand: 'right' },
    { key: 'o', finger: 'R-Ring', row: 1, hand: 'right' },
    { key: 'p', finger: 'R-Pinky', row: 1, hand: 'right' },
  ],
  [
    { key: 'a', finger: 'L-Pinky', row: 2, hand: 'left' },
    { key: 's', finger: 'L-Ring', row: 2, hand: 'left' },
    { key: 'd', finger: 'L-Middle', row: 2, hand: 'left' },
    { key: 'f', finger: 'L-Index', row: 2, hand: 'left' },
    { key: 'g', finger: 'L-Index', row: 2, hand: 'left' },
    { key: 'h', finger: 'R-Index', row: 2, hand: 'right' },
    { key: 'j', finger: 'R-Index', row: 2, hand: 'right' },
    { key: 'k', finger: 'R-Middle', row: 2, hand: 'right' },
    { key: 'l', finger: 'R-Ring', row: 2, hand: 'right' },
    { key: ';', finger: 'R-Pinky', row: 2, hand: 'right' },
  ],
  [
    { key: 'z', finger: 'L-Pinky', row: 3, hand: 'left' },
    { key: 'x', finger: 'L-Ring', row: 3, hand: 'left' },
    { key: 'c', finger: 'L-Middle', row: 3, hand: 'left' },
    { key: 'v', finger: 'L-Index', row: 3, hand: 'left' },
    { key: 'b', finger: 'L-Index', row: 3, hand: 'left' },
    { key: 'n', finger: 'R-Index', row: 3, hand: 'right' },
    { key: 'm', finger: 'R-Index', row: 3, hand: 'right' },
    { key: ',', finger: 'R-Middle', row: 3, hand: 'right' },
    { key: '.', finger: 'R-Ring', row: 3, hand: 'right' },
    { key: '/', finger: 'R-Pinky', row: 3, hand: 'right' },
  ]
];

export const LESSONS = [
  { id: 1, title: 'Index Fingers', letters: ['f', 'j'], description: 'Start with your pointer fingers on the bumps!' },
  { id: 2, title: 'Middle Fingers', letters: ['d', 'k'], description: 'Add your middle fingers.' },
  { id: 3, title: 'Ring Fingers', letters: ['s', 'l'], description: 'Now use your ring fingers.' },
  { id: 4, title: 'Pinky Fingers', letters: ['a', ';'], description: 'Stretch those pinkies!' },
  { id: 5, title: 'Home Row Master', letters: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'], description: 'Use all your fingers on the home row.' },
  { id: 6, title: 'Center Reach', letters: ['g', 'h'], description: 'Reach your index fingers to the middle.' },
  { id: 7, title: 'Top Index', letters: ['r', 'u'], description: 'Reach up with your pointers.' },
  { id: 8, title: 'Top Middle', letters: ['e', 'i'], description: 'Reach up with your middle fingers.' },
  { id: 9, title: 'Top Ring', letters: ['w', 'o'], description: 'Reach up with your ring fingers.' },
  { id: 10, title: 'Top Pinky', letters: ['q', 'p'], description: 'Reach up with your pinkies.' },
  { id: 11, title: 'Top Center', letters: ['t', 'y'], description: 'Stretch up to the middle.' },
  { id: 12, title: 'Bottom Index', letters: ['v', 'm'], description: 'Reach down with your pointers.' },
  { id: 13, title: 'Bottom Stretch', letters: ['b', 'n'], description: 'Stretch down to the middle.' },
  { id: 14, title: 'Bottom Left', letters: ['c', 'x', 'z'], description: 'Finish the bottom row left hand.' },
  { id: 15, title: 'Alphabet Challenge', letters: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'], description: 'You know them all! Type everything.' },
  { id: 16, title: 'Numbers: Left Hand', letters: ['1', '2', '3', '4', '5'], description: 'Reach way up to the numbers with your left hand!' },
  { id: 17, title: 'Numbers: Right Hand', letters: ['6', '7', '8', '9', '0'], description: 'Reach way up with your right hand!' },
  { id: 18, title: 'Numbers Master', letters: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'], description: 'Type all the numbers!' },
  { id: 19, title: 'Punctuation Party', letters: ['.', ',', ';', '/'], description: 'Use your right hand for these special marks.' },
  { id: 20, title: 'Ultimate Typer', letters: ['a', 'b', 'c', '1', '2', '3', '.', ','], description: 'Mix letters and numbers together!' },
];